#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := temperature

#EXTRA_COMPONENT_DIRS += /home/julien/projects/sandbox/esp8266/espressif/components
EXTRA_COMPONENT_DIRS += $(abspath ../components)

# COMPONENTS += DHT

include $(IDF_PATH)/make/project.mk

