include ../Makefiles/settings
include $(MAKEFILESDIR)/arduino/settings
include $(MAKEFILESDIR)/arduino/common
include $(MAKEFILESDIR)/arduino/core

all: dir $(OBJS) deps elf

NAME := compteur
SRCSDIR := .

include $(MAKEFILESDIR)/arduino/build.mk

deps:
	make -C $(MAKEFILESDIR)/arduino -f core.mk lib
	make -C $(MAKEFILESDIR)/arduino -f common.mk deps lib


