# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_statistics')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_statistics')
    _statistics = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_statistics', [dirname(__file__)])
        except ImportError:
            import _statistics
            return _statistics
        try:
            _mod = imp.load_module('_statistics', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _statistics = swig_import_helper()
    del swig_import_helper
else:
    import _statistics
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class statistics(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, statistics, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, statistics, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _statistics.new_statistics(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def reset(self):
        return _statistics.statistics_reset(self)

    def tick(self):
        return _statistics.statistics_tick(self)

    def save_eeprom(self):
        return _statistics.statistics_save_eeprom(self)

    def load_eeprom(self):
        return _statistics.statistics_load_eeprom(self)

    def day_total(self):
        return _statistics.statistics_day_total(self)

    def full_total(self):
        return _statistics.statistics_full_total(self)

    def last_minute(self):
        return _statistics.statistics_last_minute(self)

    def minute_count(self):
        return _statistics.statistics_minute_count(self)

    def get_minute(self, indx, arg3, arg4):
        return _statistics.statistics_get_minute(self, indx, arg3, arg4)

    def get_milli(self, indx):
        return _statistics.statistics_get_milli(self, indx)

    def getdata(self, Lout):
        return _statistics.statistics_getdata(self, Lout)

    def __eq__(self, other):
        return _statistics.statistics___eq__(self, other)
    if _newclass:
        test = staticmethod(_statistics.statistics_test)
    else:
        test = _statistics.statistics_test
    __swig_destroy__ = _statistics.delete_statistics
    __del__ = lambda self: None
statistics_swigregister = _statistics.statistics_swigregister
statistics_swigregister(statistics)
cvar = _statistics.cvar
NMILLIS = cvar.NMILLIS
NMINUTES = cvar.NMINUTES
NDATA = cvar.NDATA

def statistics_test():
    return _statistics.statistics_test()
statistics_test = _statistics.statistics_test

# This file is compatible with both classic and new-style classes.


