NAME:=common
MAKEFILESDIR := ../../Makefiles
SRCSDIR := .

include $(MAKEFILESDIR)/settings
include $(MAKEFILESDIR)/devhost/settings
include $(MAKEFILESDIR)/devhost/common

all: lib

include $(MAKEFILESDIR)/devhost/build.mk

