NAME:=test
MAKEFILESDIR := ../Makefiles
SRCSDIR := .

include $(MAKEFILESDIR)/settings
include $(MAKEFILESDIR)/esp8266/settings
include $(MAKEFILESDIR)/esp8266/common
include $(MAKEFILESDIR)/esp8266/core

all: dir deps $(OBJS) elf

include $(MAKEFILESDIR)/esp8266/build.mk

deps: core libs 

core:
	make -j2 -C $(MAKEFILESDIR)/esp8266 -i -f core > /dev/null 2>&1

libs:
	make -j2 -C $(MAKEFILESDIR)/esp8266 -f common lib

print:
	$(info INCLUDE is $(INCLUDE))
	$(info XINCLUDE is $(XINCLUDE))
	$(info OBJS is $(OBJS))
	$(info CXXOBJS is $(CXXOBJS))
	$(info COBJS is $(COBJS))
